import { renderWelcomePage } from '../js/components/welcome.js';
import { renderNavbar } from '../js/components/navbar.js';
import { renderStorePage } from '../js/components/store.js';
import { renderProductDetails } from '../js/components/productDetails.js';
import { renderCheckoutAddress, renderCheckoutPayment, renderOrderConfirmed } from '../js/components/checkout.js';
import { renderOrderTracking } from '../js/components/tracking.js';
import { renderMyOrders } from '../js/components/myOrders.js';
import { renderAdminDashboard } from '../js/components/admin.js';
import { renderAdminLogin } from '../js/components/adminLogin.js';
import { renderAccessDenied } from '../js/components/accessDenied.js';
import { initCartDrawer, getAppliedCoupon, setAppliedCoupon, openCart, closeCart, renderCartContents } from '../js/components/cart.js';
import { state } from '../js/state.js';
import { auth } from '../js/services/auth.js';
import { api } from '../js/services/api.js';

console.log('Testing module exports...');
console.log('✓ welcome:', typeof renderWelcomePage);
console.log('✓ navbar:', typeof renderNavbar);
console.log('✓ store:', typeof renderStorePage);
console.log('✓ productDetails:', typeof renderProductDetails);
console.log('✓ checkoutAddress:', typeof renderCheckoutAddress);
console.log('✓ checkoutPayment:', typeof renderCheckoutPayment);
console.log('✓ orderConfirmed:', typeof renderOrderConfirmed);
console.log('✓ tracking:', typeof renderOrderTracking);
console.log('✓ myOrders:', typeof renderMyOrders);
console.log('✓ admin:', typeof renderAdminDashboard);
console.log('✓ adminLogin:', typeof renderAdminLogin);
console.log('✓ accessDenied:', typeof renderAccessDenied);
console.log('✓ initCartDrawer:', typeof initCartDrawer);
console.log('✓ state:', typeof state);
console.log('✓ auth:', typeof auth);
console.log('✓ api:', typeof api);
console.log('🎉 All JavaScript module imports and exports successfully validated!');
